export const gameRules = {
    MAX_HAND_SIZE: 7,
    MAX_FIELD_SIZE: 5,
    MAX_MANA: 10,
    STARTING_HAND_SIZE: 5,
    STARTING_LIFE: 10,
    MAX_DECK_SIZE: 40,
    MANA_PER_TURN: 1,
    STARTING_MANA: 1,
    MAX_COPIES_IN_DECK: 2

};
